# 端口
server:
  port: 7777

#eureka:
#  instance:
#    # 是否使用IP地址注册
#    prefer-ip-address: false
#    # host名称
#    hostname: eureka7777.com
#  client:
#    # 是否向服务注册中心注册自己
#    register-with-eureka: false
#    # 是否检索服务 注册中心不负责检索服务 ，单点可以先关掉
#    fetch-registry: false
#    # 服务注册中心的配置内容，指定服务注册中心的位置,让别人能够找到这个注册中心
#    # 集群版eureka 要相互注册
#    server-url:
#      defaultZone: http://eureka7776.com:7776/eureka/
#  server:
#    # 是否开启自我保护
#    enable-self-preservation: false

eureka:
  instance:
    hostname: eureka7777.com
  # 声明要往哪个注册中心注册服务
  client:
    service-url:
      defaultZone: http://eureka7776.com:7776/eureka/
    register-with-eureka: false
    fetch-registry: false

  server:
    # 是否开启自我保护
    enable-self-preservation: false






