# 端口
server:
  port: 7776

spring:
  application:
    name: eureka-demo

eureka:
  client:
    # 是否向服务注册中心注册自己
    register-with-eureka: false
    # 是否检索服务 注册中心不负责检索服务 ，单点可以先关掉
    fetch-registry: false
    # 服务注册中心的配置内容，指定服务注册中心的位置,让别人能够找到这个注册中心
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${ .port}/eureka/
  server:
    # 是否开启自我保护
    enable-self-preservation: false
  instance:
    # 是否使用IP地址注册
    prefer-ip-address: true
    # host名称
    hostname: localhost




