server:
  port: 8081

spring:
  application:
    name: customer-demo

eureka:
  # 声明要往哪个注册中心注册服务
  client:
    service-url:
      defaultZone: http://eureka7776.com:7776/eureka/,http://eureka7777.com:7777/eureka/
  # 开启容错处理机制，在springboot中hystrix已经与feign集成。引入feign就已经引入hystrix
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'